openapi: 3.0.0
servers:
  - url: /api
info:
  title: basejs API
  version: 0.0.1
  description: Documentation of the RESTful API exposed by basejs
security:
  - JWT: []
paths:
  /auth/token:
    post:
      tags:
        - Authentication
      description: Create a JWT based on user credentials
      security: []
      responses:
        '200':
          description: New generated JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
        description: User credentials
        required: true
    delete:
      tags:
        - Authentication
      description: Log out a user to invalidate existing refresh tokens
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /auth/refresh/token:
    post:
      tags:
        - Authentication
      description: Create a JWT based on a refresh token
      security: []
      responses:
        '200':
          description: New generated JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
        description: refresh token
        required: true
  /auth/social/token:
    post:
      tags:
        - Authentication
      description: Create a JWT based on social provider token
      security: []
      responses:
        '200':
          description: New generated JWT
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWT'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - provider
                - token
              properties:
                provider:
                  type: string
                token:
                  type: string
        description: Social provider and its access token
        required: true
  /users:
    get:
      tags:
        - Users
      description: Get all users
      parameters:
        - $ref: '#/components/parameters/filterParam'
        - $ref: '#/components/parameters/sortParam'
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: Users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserList'
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      tags:
        - Users
      description: Create a user
      security:
        - {}
        - JWT: []
      responses:
        '201':
          description: New user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User to create
        required: true
  /users/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'
    get:
      tags:
        - Users
      description: Get a user by id
      responses:
        '200':
          description: User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          $ref: '#/components/responses/ErrorResponse'
    patch:
      tags:
        - Users
      description: Update user fields by id
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        description: User fields to update
        required: true
  /profiles/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'
    get:
      tags:
        - Users
      description: Get a user profile by id
      responses:
        '200':
          description: Profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profile'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /products:
    get:
      tags:
        - Products
      description: Get all products
      security:
        - {}
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/filterParam'
        - $ref: '#/components/parameters/sortParam'
        - $ref: '#/components/parameters/skipParam'
        - $ref: '#/components/parameters/limitParam'
      responses:
        '200':
          description: Products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
        default:
          $ref: '#/components/responses/ErrorResponse'
    post:
      tags:
        - Products
      description: Create a product
      responses:
        '201':
          description: New product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Product to create
        required: true
  /products/{id}:
    parameters:
      - $ref: '#/components/parameters/idParam'
    get:
      tags:
        - Products
      description: Get a product by id
      security:
        - {}
        - JWT: []
      responses:
        '200':
          description: Product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        default:
          $ref: '#/components/responses/ErrorResponse'
    patch:
      tags:
        - Products
      description: Update product fields by id
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Product fields to update
        required: true
    delete:
      tags:
        - Products
      description: Delete a product by id
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
  /products/{id}/owner:
    parameters:
      - $ref: '#/components/parameters/idParam'
    put:
      tags:
        - Products
      description: Replace owner of product
      responses:
        '204':
          $ref: '#/components/responses/NoContentResponse'
        default:
          $ref: '#/components/responses/ErrorResponse'
      requestBody:
        content:
          text/plain:
            schema:
              type: string
        description: New owner id
        required: true
tags: []
components:
  responses:
    NoContentResponse:
      description: OK
    ErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  parameters:
    idParam:
      name: id
      in: path
      description: id of item
      required: true
      schema:
        type: string
    filterParam:
      name: filter
      in: query
      description: 'Filter by { "field": "value", ... }'
      schema:
        type: string
    sortParam:
      name: sort
      in: query
      description: 'Sort by { "field": "asc/desc", "field": 1/-1, ... }'
      schema:
        type: string
    skipParam:
      name: skip
      in: query
      description: Number of items to skip
      schema:
        type: integer
        minimum: 0
    limitParam:
      name: limit
      in: query
      description: Number of items to return (1 - 100, default is 20)
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: Bearer
  schemas:
    User:
      type: object
      required:
        - username
      properties:
        _id:
          type: string
          readOnly: true
        username:
          type: string
        email:
          type: string
        password:
          type: string
          format: password
          writeOnly: true
        role:
          type: string
          enum:
            - user
            - moderator
            - admin
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
        logoutAt:
          type: string
          format: date-time
          readOnly: true
    UserList:
      type: array
      items:
        $ref: '#/components/schemas/User'
    Profile:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
    Product:
      type: object
      required:
        - title
      properties:
        _id:
          type: string
          readOnly: true
        title:
          type: string
        price:
          type: number
        ownerId:
          type: string
          readOnly: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    ProductList:
      type: array
      items:
        $ref: '#/components/schemas/Product'
    Error:
      type: object
      required:
        - statusCode
      properties:
        statusCode:
          type: integer
        error:
          type: string
        message:
          type: string
    JWT:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
